# clone:
#   depth: full

# pipelines:
#   default:
#     - step:
#         name: 'Mirror to Github ...'
#         script:
#           - git push --all git@github.com:robertlarocca/bitbucket-mirror-test.git
#           - git push --mirror git@github.com:robertlarocca/bitbucket-mirror-test.git

pipelines:
  default:
    - step:
        name: 'Mirror Bitbucket to Github'
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:robertlarocca/github-mirror-test.git
          - cd github-mirror-test.git
          - git push --mirror git@github.com:robertlarocca/bitbucket-mirror-test.git
