clone:
  depth: full

pipelines:
  default:
    - step:
        name: 'Mirror to Github ...'
        script:
          - git push --all git@github.com:robertlarocca/bitbucket-mirror-test.git
          - git push --mirror git@github.com:robertlarocca/bitbucket-mirror-test.git

