clone:
  depth: full

pipelines:
  default:
    - step:
        name: 'Mirror to Github repo....'
        script:
          - git push --mirror git@github.com:robertlarocca/bitbucket-mirror-test.git --all